from PyQt6.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QVBoxLayout
import sys

app = QApplication(sys.argv)

window = QWidget()
window.setWindowTitle("Penalty Game")

label = QLabel("Shoot your shot!")

btn_left = QPushButton("Left")
btn_center = QPushButton("Center")
btn_right = QPushButton("Right")

def shoot_left():
    label.setText("You shot left!")

def shoot_center():
    label.setText("You shot center!")

def shoot_right():
    label.setText("You shot right!")

btn_left.clicked.connect(shoot_left)
btn_center.clicked.connect(shoot_center)
btn_right.clicked.connect(shoot_right)

layout = QVBoxLayout()
layout.addWidget(label)
layout.addWidget(btn_left)
layout.addWidget(btn_center)
layout.addWidget(btn_right)

window.setLayout(layout)
window.show()

sys.exit(app.exec())
# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


